name: CD Pipeline

# define that the pipeline is manually triggered
on:
  workflow_dispatch:

env:
  CONTAINER_NAME: ci-cd-github-actions-fastapi-web-1
  PROJECT_PATH: C:\Users\llorenc.buil\github\CI-CD-GitHub-Actions-FastAPI

jobs:
  deploy:
    # run on production server
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Stop Docker container
        run: |
          docker stop ${{env.CONTAINER_NAME}}
        shell: cmd

      - name: Pull code
        run: |
          cd ${{env.PROJECT_PATH}}
          git pull
        shell: cmd

      - name: Install possible new libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: cmd

      - name: Run pytest on server
        run: |
          pytest
        shell: cmd

      - name: Start Docker container
        run: |
          docker compose -f docker-compose-prod.yaml up -d --build
        shell: cmd
