name: CD Pipeline

# define that the pipeline is manually triggered
on:
  workflow_dispatch:

jobs:
  deploy:
    # run on production server
    runs-on: self-hosted
    steps:
      # - name: Authenticate with token
      #   uses: actions/checkout@v3
      #   with:
      #     token: ${{ secrets.TOKEN }}
      #     fetch-depth: 0

      - name: Stop Docker container
        shell: cmd
        run: |
          FOR /F "tokens=*" %i IN ('docker ps -q') DO (docker stop %i)

      - name: Pull code
        shell: cmd
        run: |
          cd C:\Users\llorenc.buil\github\CI-CD-GitHub-Actions-FastAPI
          git pull

      - name: Install possible new libraries
        shell: cmd
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest on server
        shell: cmd
        run: |
          cd C:\Users\llorenc.buil\github\CI-CD-GitHub-Actions-FastAPI
          pytest

      - name: Start Docker container
        shell: cmd
        run: |
          docker compose -f docker-compose-prod.yaml up --build