name: CD Pipeline

# define that the pipeline is manually triggered
on:
  workflow_dispatch:

jobs:
  deploy:
    # run on production server
    runs-on: self-hosted
    steps:
      - name: Authenticate with token
        uses: actions/checkout@v3
      #   with:
      #     token: ${{ secrets.TOKEN }}
      #     fetch-depth: 0

      # - name: Stop Docker container
      #   run: |
      #     cd C:\Users\llorenc.buil\github\CI-CD-GitHub-Actions-FastAPI
      #     docker stop $(docker ps -q)
      #   shell: pwsh

      - name: Pull code
        run: |
          cd C:\Users\llorenc.buil\github\CI-CD-GitHub-Actions-FastAPI
          git pull
        shell: cmd

      # - name: Install possible new libraries
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt
      #   shell: pwsh

      # - name: Run pytest on server
      #   run: |
      #     cd C:\Users\llorenc.buil\github\CI-CD-GitHub-Actions-FastAPI
      #     pytest
      #   shell: pwsh

      # - name: Start Docker container
      #   run: |
      #     docker compose -f docker-compose-prod.yaml up --build
      #   shell: pwsh