name: CD Pipeline

# define that the pipeline is manually triggered
on:
  workflow_dispatch:

jobs:
  deploy:
    # run on production server
    runs-on: self-hosted
    steps:
      - name: Authenticate with token
        uses: actions/checkout@v3

      - name: Stop Docker container
        run: |
          cd C:\Users\llorenc.buil\github\CI-CD-GitHub-Actions-FastAPI
          docker stop ci-cd-github-actions-fastapi-web-1
        shell: cmd

      - name: Pull code
        run: |
          cd C:\Users\llorenc.buil\github\CI-CD-GitHub-Actions-FastAPI
          git pull
        shell: cmd

      - name: Install possible new libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: cmd

      - name: Run pytest on server
        run: |
          cd C:\Users\llorenc.buil\github\CI-CD-GitHub-Actions-FastAPI
          pytest
        shell: cmd

      - name: Start Docker container
        run: |
          cd C:\Users\llorenc.buil\github\CI-CD-GitHub-Actions-FastAPI
          docker compose -f docker-compose-prod.yaml up -d --build
        shell: cmd