name: CD Pipeline

# define that the pipeline is manually triggered
on:
  workflow_dispatch:

jobs:
  deploy:
    # run on production server
    runs-on: self-hosted
    steps:

      - name: Authenticate with token
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}
          fetch-depth: 0

      - name: Merge pre_master into master
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
          git checkout master
          git merge pre_master
          git push -u origin master

      - name: Pull code
        run: |
          cd C:\Users\llorenc.buil\github\CI-CD-GitHub-Actions
          git checkout master
          git clean -fd -x
          git pull

      - name: Run pytest on server
        run: |
          cd C:\Users\llorenc.buil\github\CI-CD-GitHub-Actions
          python -m pytest
