name: CD Pipeline

# define that the pipeline is manually triggered
on:
  workflow_dispatch:

jobs:
  deploy:
    # run on production server
    runs-on: self-hosted
    steps:
      # - name: Authenticate with token
      #   uses: actions/checkout@v3
      #   with:
      #     token: ${{ secrets.TOKEN }}
      #     fetch-depth: 0

      - name: Stop API
        run: |
          pkill uvicorn

      - name: Pull code
        run: |
          cd C:\Users\llorenc.buil\github\CI-CD-GitHub-Actions-FastAPI
          git pull

      - name: Run pytest on server
        run: |
          cd C:\Users\llorenc.buil\github\CI-CD-GitHub-Actions
          python -m pytest

      - name: Start API
        run: |
          uvicorn src.main:app --port 8000